=encoding utf-8

=head1 NAME

WarnMissingAttachment - Warn user when attachment keywords are mentioned but no attachment was added.

=head1 DESCRIPTION

It's not that unusual to type something like "Attached is a new version of the file", but then you forget to
attach the file before sending the mail. This add on checks the email for some keywords like "attached", 
"attachment", etc. before the message is submitted.

When those keywords are found but no attachments are uploaded, the user gets a warning.

This add on affects AgentTicketPhone, AgentTicketEmail and AgentTicketCompose.

=head1 REPOSITORY AND BUGTRACKER

The code and the bugtracker can be found at L<https://github.com/reneeb/otrs-WarnMissingAttachment>

=head1 CONTRIBUTORS

Balázs Úr, OTRS-megoldások (L<http://www.otrs-megoldasok.hu>)

 * Hungarian translation

=head1 AUTHOR AND LICENSE

Copyright (C) 2016 Renée Bäcker, L<http://perl-services.de>

This software comes with ABSOLUTELY NO WARRANTY. 
For details, see the enclosed file COPYING for 
license information (AGPL). If you did not receive 
this file, see L<http://www.gnu.org/licenses/agpl.txt>.

